### ISSUE TITLE
Utkscan and scope exit at 14% while scanning a135feb_12.ldf

### ISSUE THREAD

**Issue by sztaylor89** [pixie16/paass#228] opened 2017-02-14 20:07 UTC
When trying to run `a135feb_12.ldf` file, utkscan runs until 14%, then consumes all of the available computer memory, until ending with the message "killed".

GDB says, 

>Program terminated with signal SIGKILL, Killed. The Program no longer exists."  The backtrace gives "no stack.

**Comment by spaulaus** [comment] 2017-02-20 17:15
@sztaylor89 

Can you provide us with more details on this error? What version are you running? What LDF are you analyzing. What does your configuration look like? What computer were you using?

The more information you can provide the better.

**Comment by sztaylor89** [comment] 2017-02-20 18:23
I'm on my ANL1471 branch from my forked repo.  I last diverged from the dev branch at commit 976d769e904003234708ce6f40088f0ba76b05ee.  The file I was using is on kqxhc under `/scratch2/anl2015/FEB2015/135SB/a135feb_12.ldf`

**Comment by spaulaus** [comment] 2017-02-20 18:26
Have you rebased this branch onto dev recently?

**Comment by sztaylor89** [comment] 2017-02-20 18:26
Here's my config file(as txt)
[Config_135_121616.txt](https://github.com/pixie16/paass/files/788239/Config_135_121616.txt)

**Comment by sztaylor89** [comment] 2017-02-20 18:27
I haven't rebased since the addition of the refactoring of the channel data

**Comment by spaulaus** [comment] 2017-02-20 18:30
I would update the branch and see if that fixes your issue. I cleaned up a number of pointer issues that could have caused this behavior. This may also be related to Issue #199, but I don't have any specifics for that at the moment.

**Comment by sztaylor89** [comment] 2017-02-20 18:30
The file also causes scope to crash at 14%.

**Comment by spaulaus** [comment] 2017-02-20 21:05
@sztaylor89 Have you managed to update?

**Comment by spaulaus** [comment] 2017-03-02 12:17
I have tested this with 1f5c39ead06011a9275887ba87696f3869817c7f. The issue exists, and the program starts to have issues 14% complete. It used up all of the memory on my laptop and things became sluggish.  The program didn't crash, but it utilized all of the RAM and swap space. This suggests that there is an issue with the memory allocation, as mentioned in #199. 

I will close this issue report since it's now confirmed to be a duplicate and move the discussion to the other issue.

**Comment by spaulaus** [comment] 2017-03-02 18:36
I have tested this with 1f5c39e using a135feb_12.ldf. The program starts to have issues 14% complete. It used up all of the memory on my laptop and things became sluggish. The program didn't crash, but it utilized all of the RAM and swap space. This suggests that there is an issue with the memory allocation.

**Comment by spaulaus** [comment] 2017-03-02 18:37
Confirmed that this issue also occurs with utkscanor. This eliminates the issue being with the histogramming classes because utkscan and utkscanor use different histogramming. 

Memory usage of the program: 
![image](https://cloud.githubusercontent.com/assets/1553042/23519269/502847a0-ff44-11e6-96f1-46392672485a.png)

**Comment by spaulaus** [comment] 2017-03-02 18:37
I have tried scanning `IS599Oct_A052_02.ldf` and we get much farther than the previous ldf with no obvious memory related issues. There may be some sort of corruption in `a135feb_12.ldf` that we are not handling properly.

**Comment by spaulaus** [comment] 2017-03-02 19:07
From the damm histogram that was produced it looks like the file craps out about 400 seconds into the run.

**Comment by tking53** [comment] 2017-03-02 19:09
(copied over from  #199 )
We also discovered that `scope` also starts eating memory ~14% as well. So i think wherever the code's issue with `a135feb_12.ldf` is; it's common to `utkscan` and `scope`. There is obviously something fishy about this file. Is there a way the unpacker (guessing) could catch this, stop and move on?  It's also curious that `pixie_ldf_c` didn't see this issue (correct me if I'm wrong @sztaylor89  )

**Comment by spaulaus** [comment] 2017-03-02 19:10
There's an option to fast-forward if you know how many words you want to skip. You can also use rejection regions if you know how much time to skip.

**Comment by tking53** [comment] 2017-03-02 19:12
i was thinking preemptive rather than reactive. but i guess without knowing exactly why the file is causing issues, that may not be possible.

**Comment by spaulaus** [comment] 2017-03-02 19:13
We first have to identify exactly why it failed, then we can figure out how to recover from it.

**Comment by ksmith0** [comment] 2017-03-03 02:19
I would suggest trying to unpack the buffer headers with something like evtDump from evt2root v2 first and make sure it's not at the buffer level.

**Comment by spaulaus** [comment] 2017-03-03 13:41
Do we have any codes internal to PAASS that can handle something like this?

**Comment by ksmith0** [comment] 2017-03-07 04:27
Not that I know of. @cthornsb may have something, but I'm not sure it is built into PAASS

**Comment by spaulaus** [comment] 2017-05-25 10:25
@rin-yokoyama : Nice catch. I have tested this, and you are correct. That error boggled my mind for quite a while.

**Closed as completed** 2017-05-25 20:40 UTC
Labels: utkscan
