### ISSUE TITLE
Backspace does not delete characters

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#70] opened 2016-09-03 20:13 UTC
If I type something wrong in the prompt, I cannot backspace to delete the offending character, the backspace actually pushes me forward.

**Comment by spaulaus** [comment] 2016-09-03 20:26
I just leaned that I can use the arrow keys and the delete key to emulate the backspace functionality.

**Comment by ksmith0** [comment] 2016-09-04 01:26
Can you tell me more about when this occurred?

Perhaps try the new `CTerminalTest` program by building with the CMake option `BUILD_TESTS`

The launch CTerminalTest and type `debug` then provide the result after hitting the backspace key. Should look like this:

```
This is test terminal.
Test> debug
Debug mode is on.
TERM: Curs (6, 43) Key: 263 ^G
Test> 
```

**Comment by ksmith0** [comment] 2016-09-12 21:45
Closing as the issue is not repeatable.

**Comment by spaulaus** [comment] 2016-12-12 22:35
This issue is repeatable. I've been able to do it twice today. 

The terminal debugger provides 
For backspace key : `TERM: Curs (6-6, 22) Key: 8`
For Delete key : `TERM: Curs (7-6, 22) Key: 330 J`

**Comment by ksmith0** [comment] 2016-12-12 22:50
From ncurses.h:
```c
#define KEY_BACKSPACE   0407     /* backspace key */
...
#define KEY_DC    0512     /* delete-character key */
```
Octal code 0407 = 263 and 0512 = 220.

The odd thing is that your backspace key gives a code of 8. The code sent is dependent on the terminal used. So if you could provide which terminal you are using that would be helpful as well.

Can you provide the output of `stty -a`?
```
$ stty -a
speed 38400 baud; rows 46; columns 170; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W;
lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```

**Comment by spaulaus** [comment] 2016-12-12 22:53
My terminal is [terminology](https://www.enlightenment.org/about-terminology)
```
speed 38400 baud; rows 25; columns 119; line = 0;
intr = ^C; quit = ^\; erase = ^H; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q;
stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke 
```

**Comment by ksmith0** [comment] 2016-12-12 23:06
This is a huge bag or worms, but I suggest we trap ASCII code 8 for backspace and ASCII code 127 for delete in addition to the current values.

**Comment by spaulaus** [comment] 2016-12-12 23:07
I don't see any immediate issues there. What other codes could that interfere with?

**Comment by ksmith0** [comment] 2016-12-13 16:11
According to this fun document: http://vigna.di.unimi.it/bsdel/bsdel.pdf
Terminology may be considered a deviant terminal when discussing backspace operations. 
Can you perform the following:
* Open a new terminal
* Compile the following one line c program:
```c
void main(void) {int c; while(c = getchar()) printf("%d 0x%02X\n", c, c);}
```
* Change your backspace key:
```
stty erase "^-"
```
* Execute the one liner, hit backspace and enter and provide the results.
```
$ ./a.out 
^?
127 0x7F
10 0x0A
```

**Comment by ksmith0** [comment] 2017-02-03 16:36
Attempted to resolve this with no success. This affects a limited number of users. Closing as wontfix until others complain.

**Closed as completed by ksmith0** 2017-02-03 16:36 UTC
Labels: bug, wontfix, terminal

**Comment by tking53** [comment] 2017-02-22 18:38
additional info for reference. In a Tmux session ($TERM = xterm-256color) the `Home` and `End` keys also exhibit this behavior. However outside of a Tmux session ($TERM still = xterm-256color) they work as expected. The first image is inside Tmux `Home` then `End` (`^` is the first char of both) Second is outside tmux.

![pasted image at 2017_02_22 08_59](https://cloud.githubusercontent.com/assets/18449805/23226550/f1eef652-f903-11e6-8b17-c749cd7d1011.png)
![pasted image at 2017_02_22 08_56](https://cloud.githubusercontent.com/assets/18449805/23226556/f4c97988-f903-11e6-92a6-34f15b4676bd.png)

**Comment by ksmith0** [comment] 2017-02-22 23:50
@tking53 can you provide the tmux version used?

**Comment by ksmith0** [comment] 2017-02-22 23:53
@tking53 Can you also change your term to `screen-256color` and see if the issue goes away?

**Comment by tking53** [comment] 2017-02-23 00:00
kqxhc has tmux 1.8, my laptop has 2.2. I'll check with my laptop tomorrow.

**Comment by tking53** [comment] 2017-02-23 14:44
Yes changing term to `screen-256color` seems to have fixed the `Home` and `End` keys
