### ISSUE TITLE
Segmentation Fault when stopping run

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#86] opened 2016-09-17 17:09 UTC
I stopped an ldf run and received a segmentation fault. You can see the sequence of commands in the figure below. I believe @wapmanzoo has run into this issue before, but I cannot find an issue log for it. 
![image](https://cloud.githubusercontent.com/assets/1553042/18609746/dc8587c0-7cd7-11e6-8a08-8a94c0330748.png)

**Comment by wapmanzoo** [comment] 2016-09-17 17:32
Don't remember the specifics. The pixie16msg might have more info. If you have trouble reading the ldf then use lemor and then 

> ouf name.ldf
> That will close it so if is readable.

-Bill

William A. Peters Ph.D.
ORNL
Univ. of Tenn. 
865 576-6798

**Comment by spaulaus** [comment] 2016-09-17 17:54
I have no trouble reading the ldf or creating histograms.

**Comment by spaulaus** [comment] 2016-09-17 19:13
Had another segfault, and then could not start poll2 with the `-f` flag. Here is the relevant portion of the Pixie16Msg.txt

![image](https://cloud.githubusercontent.com/assets/1553042/18610393/52272a22-7ce9-11e6-8554-728eea590962.png)

**Comment by spaulaus** [comment] 2016-09-17 20:03
In a continuation of this issue, poll2 has frozen while stopping a run. I cannot use ctrl+c to kill, ctrl+z to suspend or any other fancy key combination to recover the terminal.

**Comment by ksmith0** [comment] 2016-09-19 16:17
`Ctrl+C` and `Ctrl+Z` are trapped by the terminal. I believe this issue is caused by the run file being closed prior to the run being ended. Introduced in commit ee8c03f4bb21160699c8625d7c98aed4367e7ef4.

**Comment by ksmith0** [comment] 2016-09-21 19:49
Should be resolved in commit b17d0f0. Closing this issue until it reappears.

**Closed as completed by ksmith0** 2016-09-21 19:49 UTC
Labels: bug, Acquisition
